config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'
  devise_for :users

  resources :users do
    resources :questions
    resources :quizzes
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :quizzes, optional: true

end

app/models/quiz.rb
class Quiz < ApplicationRecord
  has_one :question
  accepts_nested_attributes_for :question
end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!

  def index
    user = current_user
    @questions = Question.where(:user_id => user.id)
    @user = current_user
    @high_scores = User.order(score: :desc).limit(10)
    @low_scores = User.order(score: :asc).limit(10)

    @average_score = User.average(:score).round


    most_accurate_category = Quiz.group(:quiz_category).where(accuracy: true, :user_id => user.id).count
    @best_category = most_accurate_category.key(most_accurate_category.values.max)

   
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user_id = current_user.id
    
    if @question.save
      flash[:alert] = 'Question saved successfully!'
      redirect_to new_user_question_path
    else 
      flash[:alert] = 'Question could not be saved'
      redirect_to new_user_question_path
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])

    if @question.update!(question_params)
      flash[:alert] = 'Question updated successfully!'
      redirect_to user_question_path(current_user, @question)
    else
      flash[:alert] = 'Question could not be updated!'
      render 'edit'
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy!

    redirect_to root_path(current_user)
  end

  private
  def question_params
    params.require(:question).permit( :question, :correct_answer, :category, :user_id, :answer_option_one, :answer_option_two,
    :answer_option_three)
  end

end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :authenticate_user!

  def index
    @quizzes = Quiz.all
    @quiz = Quiz.new
  end

  def show
    @quiz = Quiz.find(params[:id])
    @questions = Question.where(:id => @quiz.question_id)
    @answers = Question.where(:id => @quiz.question_id)
    questions_to_hash = @questions.as_json
    current_question = questions_to_hash[0]["id"]
    @quiz.question_id = current_question

    @answers = [questions_to_hash[0]["correct_answer"], 
                questions_to_hash[0]["answer_option_one"], 
                questions_to_hash[0]["answer_option_two"],
                questions_to_hash[0]["answer_option_three"]].shuffle
  end

  def new
    @quiz = Quiz.new
  end

  def create
    @quiz = Quiz.new(quiz_params)
    @quiz.user_id = current_user.id

    @questions = Question.where(:category => @quiz.quiz_category).order("random()").limit(1)
    questions_to_hash = @questions.as_json
    current_question = questions_to_hash[0]["id"]
    @quiz.question_id = current_question

    if @quiz.save
      flash[:alert] = 'Good Luck!'
      redirect_to user_quiz_path(current_user, @quiz)
    end
  end


  def edit
    @quiz = Quiz.find(params[:id])
  end

  def update
    @quiz = Quiz.find(params[:id])
    @question = Question.where(:id => @quiz.question_id)
    correct_to_hash = @question.as_json
    correct = correct_to_hash[0]["correct_answer"]
    @user = current_user

    if @quiz.update!(quiz_params) && @quiz.guess == correct
      @quiz.accuracy = true
      @quiz.save!
      @user.score += 4
      @user.save!
      flash[:alert] = 'You got it right! Try another one below'
      redirect_to user_quizzes_path(current_user, @quiz)
    elsif @quiz.update!(quiz_params) && @quiz.guess != correct
      @quiz.accuracy = false
      @quiz.save!
      @user.score -= 1
      @user.save!
      flash[:alert] = "The correct answer was #{correct}. You guessed #{@quiz.guess}.Try another one below"
      redirect_to user_quizzes_path(current_user, @quiz)
    else
      flash[:alert] = 'Quiz could not be submitted!'
      render 'edit'
    end
  end


  private
  def quiz_params
    params.require(:quiz).permit(:score, :quiz_category, :user_id, :running_score, :question_id, :guess)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TriviaApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div  class="alert alert-primary">
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>

</html>

app/views/questions/edit.html.erb
<div class = "navbar navbar-light bg-dark text-center">
<h1>Edit Question</h1>
<%= link_to "Log Out", destroy_user_session_path, method: :delete, :class => "btn-logout" %>
</div>

<body class = "text-center select">
<%= form_for @question, url: user_question_path do |form| %>
 
  <%= form.label :category %>:
  <%= form.select(:category, options_for_select([['History'], ['Science'], ['Entertainment'], ['Sports'], ['Geography']])) %><br>
  <%= form.label :question %>:
  <%= form.label :correct_answer %>:
  <%= form.text_field :correct_answer %><br>
  <%= form.label :answer_option_one %>:
  <%= form.text_field :answer_option_one %><br>
  <%= form.label :answer_option_two %>:
  <%= form.text_field :answer_option_two %><br>
  <%= form.label :answer_option_three %>:
  <%= form.text_field :answer_option_three %><br>
  <%= form.submit 'Update', :class => "btn" %>
<% end %>
 
<%= link_to 'Back', user_questions_path, :class => "btn" %>
</body>

app/views/questions/index.html.erb
<div class = "navbar navbar-light bg-dark">
<h1>Welcome, <%= current_user.email %>! </h1> 
<%= link_to "Log Out", destroy_user_session_path, method: :delete, :class => "btn-logout" %>
</div>

<h2><%= link_to 'Start Trivia', user_quizzes_path(current_user, @questions),:class => "btn" %></h2>

<div class = "nav">
  <table class = "table-bordered table-hover mx-auto w-auto">
  <tr>
    <th>You're current score is: </th>
  </tr>
    <td><%= @user.score %></td>
</table>

<table class = "table-bordered table-hover mx-auto w-auto">
  <tr>
    <th> Your best category: </th>
  </tr>
    <td><%= @best_category%></td>
</table>

<table class = "table-bordered table-hover mx-auto w-auto">
  <tr>
    <th> Leaderboard </th>
    <th> Score</th>
  </tr>
    <% @high_scores.each do |user|%>
  <tr>
    <td><%= user.email%></td>
    <td><%= user.score%></td>
  </tr>
  <%end%>
</table>
<table class = "table-bordered table-hover mx-auto w-auto">
  <tr>
    <th> Underdogs </th>
    <th> Score</th>
  </tr>
    <% @low_scores.each do |user|%>
  <tr>
    <td><%= user.email%></td>
    <td><%= user.score%></td>
  </tr>
  <%end%>
</table>

<table class = "table-bordered table-hover mx-auto w-auto">
  <tr>
    <th> The Average Player Score: </th>
  </tr>
    <td><%= @average_score%></td>
</table>
</div>
<br>
<body class = "text-center select">
<h4> Here are all of the questions you have contributed. Create, edit, or delete a question below! </h4>
<h2><%= link_to "Create a new question", new_user_question_path(current_user, @question), :class => "btn" %></h2>

<br>
<table class = "table table-bordered table-striped">
  <tr>
    <th>Category</th>
    <th>Question</th>
    <th>Correct Answer</th>
    <th>Answer Option One</th>
    <th>Answer Option Two</th>
    <th>Answer Option Two</th>
    <th>Edit</th>
    <th>Delete</th>

  </tr>

  <% @questions.each do |question| %>
    <tr>
      <td><%= question.category %></td>
      <td><%= question.question %></td>
      <td><%= question.correct_answer %></td>
      <td><%= question.answer_option_one %></td>
      <td><%= question.answer_option_two %></td>
      <td><%= question.answer_option_three %></td>

      <td><%= link_to 'Edit', edit_user_question_path(current_user, question), :class => "btn" %></td>
      <td><%= link_to 'Delete', user_question_path(current_user, question),
              method: :delete,
              data: { confirm: 'Are you sure?' },:class => "btn" %></td>
    </tr>
  <% end %>
</table>
<br>


</div>
</body>

app/views/questions/new.html.erb
<div class = "navbar navbar-light bg-dark text-center">
<h1> Create A Question </h1>
<%= link_to "Log Out", destroy_user_session_path, method: :delete, :class => "btn-logout" %>
</div>

<body class = "text-center select">
<%= form_for @question, url: user_questions_path do |f| %>
  <%= f.label :category %>:
  <%= f.select(:category, options_for_select([['History'], ['Science'], ['Entertainment'], ['Sports'], ['Geography']]))  %><br>
  <%= f.label :question %>:
  <%= f.text_field :question %><br>
  <%= f.label :correct_answer %>:
  <%= f.text_field :correct_answer %><br>
  <%= f.label :answer_option_one %>:
  <%= f.text_field :answer_option_one %><br>
  <%= f.label :answer_option_two %>:
  <%= f.text_field :answer_option_two %><br>
  <%= f.label :answer_option_three %>:
  <%= f.text_field :answer_option_three %><br>
  <%= f.submit "Create", :class => "btn" %>
<% end %>

<%= link_to 'Back', user_questions_path, :class => "btn" %>

</body>

app/views/questions/show.html.erb
<div class = "navbar navbar-light bg-dark text-center">
<h1>Your Question</h1>
<%= link_to "Log Out", destroy_user_session_path, method: :delete, :class => "btn-logout" %>
</div>

<body class = "select text-center">
<p>
  <strong>Category:</strong>
  <%= @question.category %>
</p>
 
<p>
  <strong>Question:</strong>
  <%= @question.question %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @question.correct_answer %>
</p>

<p>
  <strong>Wrong Answer One:</strong>
  <%= @question.answer_option_one %>
</p>

<p>
  <strong>Wrong Answer Two:</strong>
  <%= @question.answer_option_two %>
</p>

<p>
  <strong>Wrong Answer Three:</strong>
  <%= @question.answer_option_three %>
</p>

 <td><%= link_to 'Home Page', root_path(current_user), :class => "btn" %></td>
 </body>

app/views/quizzes/edit.html.erb
<h1> Show quiz score here? </h1>

app/views/quizzes/index.html.erb
<nav class = "navbar navbar-light bg-dark">
<h1> Select A Quiz Category </h1>
<%= link_to "Log Out", destroy_user_session_path, method: :delete, :class => "btn-logout" %>
</nav>

<body class = "select text-center">
  <div class = "text-center">
    <%= form_for @quiz, url: user_quizzes_path, method: :post do |f| %>
    <h3><%= f.label :quiz_category %>:</h3>
  <br>
      <div class = "dropdown">
      <%= f.select(:quiz_category, options_for_select([['History'], ['Science'], ['Entertainment'], ['Sports'], ['Geography']])) %>
      </div>
  <br>
    <%= f.submit 'Start Trivia', :class => "btn"%>
    <% end %>
    <%= link_to  'Back', user_questions_path, :class => "btn" %>
  </div>
</body>

app/views/quizzes/show.html.erb
<div class = "navbar navbar-light bg-dark text-center">
  <h1> Answer Quiz Here </h1>
  <%= link_to "Log Out", destroy_user_session_path, method: :delete, :class => "btn-logout" %>
</div>

<body class = "select text-center">
<br>

<div class = "text-center">
<% @questions.each do |question| %>
    <h2><%= question.question %><br></h2>
<% end %>

<% @answers.each do |answer| %>
    <h4><%= answer %><br></h4>
  <% end %>

<%= form_for @quiz, url: user_quiz_path(current_user, @quiz) do |f| %>
  <%= f.select(:guess, options_for_select(@answers))%>
  <br>
  <%= f.submit 'Submit Guess', :class => "btn"%>
<% end %>

<%= link_to 'Back', user_questions_path, :class => "btn" %>
</div>
</body>